services:
  - type: web
    name: shopify-daily-sales
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # 如用 gunicorn，请改为：gunicorn app:app
